import generate from "@babel/generator"
import * as t from "@babel/types"
import {
  buildConvexHookApiModel,
  type ConvexHookApiModel,
  type HookApiModelEntry,
  type HookApiModelSection,
} from "./model"
import type { ConvexFunctionKind, ConvexModuleDefinition } from "./types"

const generatedHeader = `/* eslint-disable */
/**
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run: bun run generate:convex-hook-api
 */`

export function generateConvexHookApiSource(modules: ConvexModuleDefinition[]) {
  return generateConvexHookApiSourceFromModel(buildConvexHookApiModel(modules))
}

export function generateConvexHookApiSourceFromModel(
  model: ConvexHookApiModel,
) {
  return printConvexHookApiAst(generateConvexHookApiAstFromModel(model))
}

export function generateConvexHookApiAst(modules: ConvexModuleDefinition[]) {
  return generateConvexHookApiAstFromModel(buildConvexHookApiModel(modules))
}

export function generateConvexHookApiAstFromModel(model: ConvexHookApiModel) {
  return t.file(
    t.program([
      ...buildImports(model),
      buildQueryDependencyTypeAlias(),
      buildMutationDependencyTypeAlias(),
      ...(model.hasActions ? [buildActionDependencyTypeAlias()] : []),
      buildConvexDependenciesTypeAlias(model.sections),
      buildDefaultHookApiDeclaration(),
      buildHookApiContextDeclaration(),
      buildProviderDeclaration(),
      buildUseApiDependenciesDeclaration(),
      buildUseAuthActionsDeclaration(),
      buildUseAuthStateDeclaration(),
      ...buildGeneratedHookDeclarations(model.sections),
      buildHookApiExportDeclaration(model.sections),
    ]),
  )
}

export function printConvexHookApiAst(ast: t.File) {
  const generatedSource = generate(ast, {
    comments: true,
    compact: false,
    concise: false,
    retainLines: false,
  }).code

  return `${generatedHeader}\n\n${stripStatementSemicolons(generatedSource)}\n`
}

function buildImports(model: ConvexHookApiModel): t.ImportDeclaration[] {
  return [
    t.importDeclaration(
      [t.importSpecifier(t.identifier("api"), t.identifier("api"))],
      t.stringLiteral("../../convex/_generated/api"),
    ),
    t.importDeclaration(
      [
        t.importSpecifier(
          t.identifier("useBaseConvexAuthActions"),
          t.identifier("useAuthActions"),
        ),
      ],
      t.stringLiteral("@convex-dev/auth/react"),
    ),
    t.importDeclaration(
      model.convexReactImports.map((entry) =>
        buildPossiblyTypeImportSpecifier(entry),
      ),
      t.stringLiteral("convex/react"),
    ),
    t.importDeclaration(
      [
        t.importSpecifier(
          t.identifier("FunctionReference"),
          t.identifier("FunctionReference"),
        ),
      ],
      t.stringLiteral("convex/server"),
    ),
    t.importDeclaration(
      [
        t.importSpecifier(
          t.identifier("createContext"),
          t.identifier("createContext"),
        ),
        withTypeImport(
          t.importSpecifier(
            t.identifier("ReactNode"),
            t.identifier("ReactNode"),
          ),
        ),
        t.importSpecifier(
          t.identifier("useContext"),
          t.identifier("useContext"),
        ),
      ],
      t.stringLiteral("react"),
    ),
  ]
}

function buildQueryDependencyTypeAlias() {
  return t.tsTypeAliasDeclaration(
    t.identifier("QueryDependency"),
    t.tsTypeParameterDeclaration([
      t.tsTypeParameter(
        t.tsTypeReference(
          t.identifier("FunctionReference"),
          t.tsTypeParameterInstantiation([
            t.tsLiteralType(t.stringLiteral("query")),
          ]),
        ),
        undefined,
        "Query",
      ),
    ]),
    t.tsFunctionType(
      undefined,
      [
        withTypeAnnotation(
          t.restElement(t.identifier("args")),
          t.tsTypeReference(
            t.identifier("OptionalRestArgsOrSkip"),
            t.tsTypeParameterInstantiation([
              t.tsTypeReference(t.identifier("Query")),
            ]),
          ),
        ),
      ],
      t.tsTypeAnnotation(
        t.tsUnionType([
          t.tsIndexedAccessType(
            t.tsTypeReference(t.identifier("Query")),
            t.tsLiteralType(t.stringLiteral("_returnType")),
          ),
          t.tsUndefinedKeyword(),
        ]),
      ),
    ),
  )
}

function buildMutationDependencyTypeAlias() {
  return t.tsTypeAliasDeclaration(
    t.identifier("MutationDependency"),
    t.tsTypeParameterDeclaration([
      t.tsTypeParameter(
        t.tsTypeReference(
          t.identifier("FunctionReference"),
          t.tsTypeParameterInstantiation([
            t.tsLiteralType(t.stringLiteral("mutation")),
          ]),
        ),
        undefined,
        "Mutation",
      ),
    ]),
    t.tsFunctionType(
      undefined,
      [],
      t.tsTypeAnnotation(
        t.tsTypeReference(
          t.identifier("ReactMutation"),
          t.tsTypeParameterInstantiation([
            t.tsTypeReference(t.identifier("Mutation")),
          ]),
        ),
      ),
    ),
  )
}

function buildActionDependencyTypeAlias() {
  return t.tsTypeAliasDeclaration(
    t.identifier("ActionDependency"),
    t.tsTypeParameterDeclaration([
      t.tsTypeParameter(
        t.tsTypeReference(
          t.identifier("FunctionReference"),
          t.tsTypeParameterInstantiation([
            t.tsLiteralType(t.stringLiteral("action")),
          ]),
        ),
        undefined,
        "Action",
      ),
    ]),
    t.tsFunctionType(
      undefined,
      [],
      t.tsTypeAnnotation(
        t.tsTypeReference(
          t.identifier("ReactAction"),
          t.tsTypeParameterInstantiation([
            t.tsTypeReference(t.identifier("Action")),
          ]),
        ),
      ),
    ),
  )
}

function buildConvexDependenciesTypeAlias(sections: HookApiModelSection[]) {
  return t.tsTypeAliasDeclaration(
    t.identifier("ConvexDependencies"),
    undefined,
    t.tsTypeLiteral([
      t.tsPropertySignature(
        t.identifier("auth"),
        t.tsTypeAnnotation(
          t.tsTypeLiteral([
            optionalTsProperty(
              "actions",
              t.tsFunctionType(
                undefined,
                [],
                t.tsTypeAnnotation(
                  t.tsTypeReference(
                    t.identifier("ReturnType"),
                    t.tsTypeParameterInstantiation([
                      t.tsTypeQuery(t.identifier("useBaseConvexAuthActions")),
                    ]),
                  ),
                ),
              ),
            ),
            optionalTsProperty(
              "state",
              t.tsFunctionType(
                undefined,
                [],
                t.tsTypeAnnotation(
                  t.tsTypeReference(
                    t.identifier("ReturnType"),
                    t.tsTypeParameterInstantiation([
                      t.tsTypeQuery(t.identifier("useConvexAuth")),
                    ]),
                  ),
                ),
              ),
            ),
          ]),
        ),
      ),
      ...sections.map(buildDependencySectionSignature),
    ]),
  )
}

function buildDependencySectionSignature(section: HookApiModelSection) {
  return optionalTsProperty(
    section.collectionName,
    t.tsTypeLiteral(
      section.modules.map((moduleDefinition) =>
        optionalTsProperty(
          moduleDefinition.name,
          t.tsTypeLiteral(
            moduleDefinition.entries.map((entry) => {
              const [moduleName, exportName] = getReferenceParts(
                entry.referencePath,
              )

              return optionalTsProperty(
                entry.exportName,
                t.tsTypeReference(
                  t.identifier(section.dependencyTypeName),
                  t.tsTypeParameterInstantiation([
                    t.tsTypeQuery(
                      makeApiReferenceEntityName(moduleName, exportName),
                    ),
                  ]),
                ),
              )
            }),
          ),
        ),
      ),
    ),
  )
}

function buildDefaultHookApiDeclaration() {
  return t.variableDeclaration("const", [
    t.variableDeclarator(
      t.identifier("defaultHookApi"),
      t.objectExpression([]),
    ),
  ])
}

function buildHookApiContextDeclaration() {
  return t.variableDeclaration("const", [
    t.variableDeclarator(
      t.identifier("HookApiContext"),
      t.callExpression(t.identifier("createContext"), [
        t.tsAsExpression(
          t.identifier("defaultHookApi"),
          t.tsTypeReference(t.identifier("ConvexDependencies")),
        ),
      ]),
    ),
  ])
}

function buildProviderDeclaration() {
  return t.functionDeclaration(
    t.identifier("HookApiProvider"),
    [
      withTypeAnnotation(
        t.objectPattern([
          t.objectProperty(
            t.identifier("children"),
            t.identifier("children"),
            false,
            true,
          ),
          t.objectProperty(
            t.identifier("value"),
            t.identifier("value"),
            false,
            true,
          ),
        ]),
        t.tsTypeLiteral([
          t.tsPropertySignature(
            t.identifier("children"),
            t.tsTypeAnnotation(t.tsTypeReference(t.identifier("ReactNode"))),
          ),
          t.tsPropertySignature(
            t.identifier("value"),
            t.tsTypeAnnotation(
              t.tsTypeReference(t.identifier("ConvexDependencies")),
            ),
          ),
        ]),
      ),
    ],
    t.blockStatement([
      t.returnStatement(
        t.jsxElement(
          t.jsxOpeningElement(
            t.jsxMemberExpression(
              t.jsxIdentifier("HookApiContext"),
              t.jsxIdentifier("Provider"),
            ),
            [
              t.jsxAttribute(
                t.jsxIdentifier("value"),
                t.jsxExpressionContainer(t.identifier("value")),
              ),
            ],
            false,
          ),
          t.jsxClosingElement(
            t.jsxMemberExpression(
              t.jsxIdentifier("HookApiContext"),
              t.jsxIdentifier("Provider"),
            ),
          ),
          [t.jsxExpressionContainer(t.identifier("children"))],
        ),
      ),
    ]),
  )
}

function buildUseApiDependenciesDeclaration() {
  return t.functionDeclaration(
    t.identifier("useApiDependencies"),
    [],
    t.blockStatement([
      t.returnStatement(
        t.callExpression(t.identifier("useContext"), [
          t.identifier("HookApiContext"),
        ]),
      ),
    ]),
  )
}

function buildUseAuthActionsDeclaration() {
  return t.functionDeclaration(
    t.identifier("useAuthActions"),
    [],
    t.blockStatement([
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("overrides"),
          t.callExpression(t.identifier("useApiDependencies"), []),
        ),
      ]),
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("authActions"),
          t.callExpression(t.identifier("useBaseConvexAuthActions"), []),
        ),
      ]),
      t.returnStatement(
        t.logicalExpression(
          "??",
          t.optionalCallExpression(
            t.optionalMemberExpression(
              t.memberExpression(
                t.identifier("overrides"),
                t.identifier("auth"),
              ),
              t.identifier("actions"),
              false,
              true,
            ),
            [],
            true,
          ),
          t.identifier("authActions"),
        ),
      ),
    ]),
  )
}

function buildUseAuthStateDeclaration() {
  return t.functionDeclaration(
    t.identifier("useAuthState"),
    [],
    t.blockStatement([
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("overrides"),
          t.callExpression(t.identifier("useApiDependencies"), []),
        ),
      ]),
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("authState"),
          t.callExpression(t.identifier("useConvexAuth"), []),
        ),
      ]),
      t.returnStatement(
        t.logicalExpression(
          "??",
          t.optionalCallExpression(
            t.optionalMemberExpression(
              t.memberExpression(
                t.identifier("overrides"),
                t.identifier("auth"),
              ),
              t.identifier("state"),
              false,
              true,
            ),
            [],
            true,
          ),
          t.identifier("authState"),
        ),
      ),
    ]),
  )
}

function buildGeneratedHookDeclarations(sections: HookApiModelSection[]) {
  return sections.flatMap((section) =>
    section.modules.flatMap((moduleDefinition) =>
      moduleDefinition.entries.map((entry) =>
        buildGeneratedHookDeclaration(
          section.kind,
          section.collectionName,
          moduleDefinition.name,
          entry,
        ),
      ),
    ),
  )
}

function buildGeneratedHookDeclaration(
  kind: ConvexFunctionKind,
  collectionName: HookApiModelSection["collectionName"],
  moduleName: string,
  entry: HookApiModelEntry,
) {
  const [, exportName] = getReferenceParts(entry.referencePath)
  const reference = makeApiReferenceExpression(moduleName, exportName)
  const overrideReference = makeOverrideReference(
    collectionName,
    moduleName,
    entry.exportName,
  )

  if (kind === "query") {
    return t.functionDeclaration(
      t.identifier(entry.implementationHookName),
      [
        withTypeAnnotation(
          t.restElement(t.identifier("args")),
          t.tsTypeReference(
            t.identifier("OptionalRestArgsOrSkip"),
            t.tsTypeParameterInstantiation([
              t.tsTypeQuery(makeApiReferenceEntityName(moduleName, exportName)),
            ]),
          ),
        ),
      ],
      t.blockStatement([
        t.variableDeclaration("const", [
          t.variableDeclarator(
            t.identifier("overrides"),
            t.callExpression(t.identifier("useApiDependencies"), []),
          ),
        ]),
        t.variableDeclaration("const", [
          t.variableDeclarator(t.identifier("override"), overrideReference),
        ]),
        t.variableDeclaration("const", [
          t.variableDeclarator(
            t.identifier("queryResult"),
            t.callExpression(t.identifier("useQuery"), [
              reference,
              t.memberExpression(
                t.identifier("args"),
                t.numericLiteral(0),
                true,
              ),
            ]),
          ),
        ]),
        t.ifStatement(
          t.identifier("override"),
          t.blockStatement([
            t.returnStatement(
              t.callExpression(t.identifier("override"), [
                t.spreadElement(t.identifier("args")),
              ]),
            ),
          ]),
        ),
        t.returnStatement(t.identifier("queryResult")),
      ]),
    )
  }

  if (kind === "mutation") {
    return t.functionDeclaration(
      t.identifier(entry.implementationHookName),
      [],
      t.blockStatement([
        t.variableDeclaration("const", [
          t.variableDeclarator(
            t.identifier("overrides"),
            t.callExpression(t.identifier("useApiDependencies"), []),
          ),
        ]),
        t.variableDeclaration("const", [
          t.variableDeclarator(t.identifier("override"), overrideReference),
        ]),
        t.variableDeclaration("const", [
          t.variableDeclarator(
            t.identifier("mutation"),
            t.callExpression(t.identifier("useMutation"), [reference]),
          ),
        ]),
        t.ifStatement(
          t.identifier("override"),
          t.blockStatement([
            t.returnStatement(t.callExpression(t.identifier("override"), [])),
          ]),
        ),
        t.returnStatement(t.identifier("mutation")),
      ]),
    )
  }

  return t.functionDeclaration(
    t.identifier(entry.implementationHookName),
    [],
    t.blockStatement([
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("overrides"),
          t.callExpression(t.identifier("useApiDependencies"), []),
        ),
      ]),
      t.variableDeclaration("const", [
        t.variableDeclarator(t.identifier("override"), overrideReference),
      ]),
      t.variableDeclaration("const", [
        t.variableDeclarator(
          t.identifier("action"),
          t.callExpression(t.identifier("useAction"), [reference]),
        ),
      ]),
      t.ifStatement(
        t.identifier("override"),
        t.blockStatement([
          t.returnStatement(t.callExpression(t.identifier("override"), [])),
        ]),
      ),
      t.returnStatement(t.identifier("action")),
    ]),
  )
}

function buildHookApiExportDeclaration(sections: HookApiModelSection[]) {
  return t.exportNamedDeclaration(
    t.variableDeclaration("const", [
      t.variableDeclarator(
        t.identifier("hookApi"),
        t.objectExpression([
          t.objectProperty(
            t.identifier("Provider"),
            t.identifier("HookApiProvider"),
          ),
          t.objectProperty(
            t.identifier("useDependencies"),
            t.identifier("useApiDependencies"),
          ),
          t.objectProperty(
            t.identifier("auth"),
            t.objectExpression([
              t.objectProperty(
                t.identifier("useActions"),
                t.identifier("useAuthActions"),
              ),
              t.objectProperty(
                t.identifier("useState"),
                t.identifier("useAuthState"),
              ),
            ]),
          ),
          ...sections.map((section) =>
            t.objectProperty(
              t.identifier(section.collectionName),
              t.objectExpression(
                section.modules.map((moduleDefinition) =>
                  t.objectProperty(
                    t.identifier(moduleDefinition.name),
                    t.objectExpression(
                      moduleDefinition.entries.map((entry) =>
                        t.objectProperty(
                          t.identifier(entry.publicHookName),
                          t.identifier(entry.implementationHookName),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ]),
      ),
    ]),
  )
}

function buildPossiblyTypeImportSpecifier(entry: string) {
  if (entry.startsWith("type ")) {
    const name = entry.slice("type ".length)

    return withTypeImport(
      t.importSpecifier(t.identifier(name), t.identifier(name)),
    )
  }

  return t.importSpecifier(t.identifier(entry), t.identifier(entry))
}

function withTypeImport(specifier: t.ImportSpecifier) {
  specifier.importKind = "type"

  return specifier
}

function optionalTsProperty(name: string, typeAnnotation: t.TSType) {
  const property = t.tsPropertySignature(
    t.identifier(name),
    t.tsTypeAnnotation(typeAnnotation),
  )
  property.optional = true

  return property
}

function withTypeAnnotation<T extends t.PatternLike>(
  pattern: T,
  typeAnnotation: t.TSType,
) {
  pattern.typeAnnotation = t.tsTypeAnnotation(typeAnnotation)

  return pattern
}

function makeApiReferenceExpression(moduleName: string, exportName: string) {
  return t.memberExpression(
    t.memberExpression(t.identifier("api"), t.identifier(moduleName)),
    t.identifier(exportName),
  )
}

function makeApiReferenceEntityName(moduleName: string, exportName: string) {
  return t.tsQualifiedName(
    t.tsQualifiedName(t.identifier("api"), t.identifier(moduleName)),
    t.identifier(exportName),
  )
}

function makeOverrideReference(
  collectionName: HookApiModelSection["collectionName"],
  moduleName: string,
  exportName: string,
) {
  return t.optionalMemberExpression(
    t.optionalMemberExpression(
      t.memberExpression(
        t.identifier("overrides"),
        t.identifier(collectionName),
      ),
      t.identifier(moduleName),
      false,
      true,
    ),
    t.identifier(exportName),
    false,
    true,
  )
}

function getReferenceParts(referencePath: string) {
  const parts = referencePath.split(".")

  if (parts.length !== 3 || parts[0] !== "api") {
    throw new Error(`Unsupported api reference path: ${referencePath}`)
  }

  return [parts[1], parts[2]] as const
}

function stripStatementSemicolons(source: string) {
  return source.replace(/;$/gmu, "")
}
