import generate from "@babel/generator"
import * as BabelParser from "@babel/parser"
import type { File } from "@babel/types"
import { outdent } from "outdent"
import {
  buildConvexHookApiModel,
  type ConvexHookApiModel,
  type HookApiModelEntry,
  type HookApiModelSection,
} from "./model"
import type { ConvexModuleDefinition } from "./types"

const generatedHeader = outdent`
  /* eslint-disable */
  /**
   * THIS FILE IS AUTOMATICALLY GENERATED.
   *
   * To regenerate, run: bun run generate:convex-dependencies
   */
`

const parserOptions = {
  plugins: ["typescript", "jsx"],
  sourceType: "module",
} satisfies BabelParser.ParserOptions

export function generateConvexHookApiSource(modules: ConvexModuleDefinition[]) {
  return generateConvexHookApiSourceFromModel(buildConvexHookApiModel(modules))
}

export function generateConvexHookApiSourceFromModel(
  model: ConvexHookApiModel,
) {
  return printConvexHookApiAst(generateConvexHookApiAstFromModel(model))
}

export function generateConvexHookApiAst(modules: ConvexModuleDefinition[]) {
  return generateConvexHookApiAstFromModel(buildConvexHookApiModel(modules))
}

export function generateConvexHookApiAstFromModel(model: ConvexHookApiModel) {
  const dependencyTypeDefinitions = [
    `type QueryDependency<Query extends FunctionReference<"query">> = (...args: OptionalRestArgsOrSkip<Query>) => Query["_returnType"] | undefined`,
    `type MutationDependency<Mutation extends FunctionReference<"mutation">> = () => ReactMutation<Mutation>`,
    model.hasActions
      ? `type ActionDependency<Action extends FunctionReference<"action">> = () => ReactAction<Action>`
      : null,
  ].filter((definition) => definition !== null)
  const generatedHooks = model.sections.flatMap((section) =>
    section.modules.flatMap((moduleDefinition) =>
      moduleDefinition.entries.map((entry) =>
        renderGeneratedHook(section, entry),
      ),
    ),
  )

  const source = [
    renderImports(model),
    dependencyTypeDefinitions.join("\n\n"),
    renderConvexDependenciesType(model.sections),
    `const defaultHookApi = {}`,
    `const HookApiContext = createContext<ConvexDependencies>(defaultHookApi)`,
    renderProvider(),
    renderUseApiDependencies(),
    renderUseAuthActions(),
    renderUseAuthState(),
    generatedHooks.join("\n\n"),
    renderHookApiObject(model.sections),
  ]
    .filter((section) => section.length > 0)
    .join("\n\n")

  return BabelParser.parse(source, parserOptions)
}

export function printConvexHookApiAst(ast: BabelParser.ParseResult<File>) {
  const generatedSource = generate(ast, {
    comments: true,
    compact: false,
    concise: false,
    retainLines: false,
  }).code

  return `${generatedHeader}\n\n${stripStatementSemicolons(generatedSource)}\n`
}

function renderImports(model: ConvexHookApiModel) {
  return outdent`
    import { api } from "../../convex/_generated/api"
    import { useAuthActions as useBaseConvexAuthActions } from "@convex-dev/auth/react"
    import {
      ${model.convexReactImports.join(",\n  ")},
    } from "convex/react"
    import type { FunctionReference } from "convex/server"
    import { createContext, type ReactNode, useContext } from "react"
  `
}

function renderConvexDependenciesType(sections: HookApiModelSection[]) {
  return outdent`
    type ConvexDependencies = {
      auth?: {
        actions?: () => ReturnType<typeof useBaseConvexAuthActions>
        state?: () => ReturnType<typeof useConvexAuth>
      }
    ${sections.map(renderDependencyTypeSection).join("\n")}
    }
  `
}

function renderDependencyTypeSection(section: HookApiModelSection) {
  const moduleBlocks = section.modules.map((moduleDefinition) => {
    const exportLines = moduleDefinition.entries
      .map(
        (entry) =>
          outdent`
            ${entry.exportName}?: ${section.dependencyTypeName}<${entry.referenceType}>
          `,
      )
      .join("\n")

    return outdent`
      ${moduleDefinition.name}?: {
        ${exportLines}
      }
    `
  })

  return outdent`
    ${section.collectionName}?: {
      ${moduleBlocks.join("\n")}
    }
  `
}

function renderProvider() {
  return outdent`
    function HookApiProvider({
      children,
      value,
    }: {
      children: ReactNode
      value: ConvexDependencies
    }) {
      return (
        <HookApiContext.Provider value={value}>
          {children}
        </HookApiContext.Provider>
      )
    }
  `
}

function renderUseApiDependencies() {
  return outdent`
    function useApiDependencies() {
      return useContext(HookApiContext)
    }
  `
}

function renderUseAuthActions() {
  return outdent`
    function useAuthActions() {
      const overrides = useApiDependencies()
      const authActions = useBaseConvexAuthActions()

      return overrides.auth?.actions?.() ?? authActions
    }
  `
}

function renderUseAuthState() {
  return outdent`
    function useAuthState() {
      const overrides = useApiDependencies()
      const authState = useConvexAuth()

      return overrides.auth?.state?.() ?? authState
    }
  `
}

function renderGeneratedHook(
  section: HookApiModelSection,
  entry: HookApiModelEntry,
) {
  if (section.kind === "query") {
    return outdent`
      function ${entry.implementationHookName}(
        ...args: OptionalRestArgsOrSkip<typeof ${entry.referencePath}>
      ) {
        const overrides = useApiDependencies()
        const override = ${entry.overridePath}
        const queryResult = useQuery(${entry.referencePath}, args[0])

        if (override) {
          return override(...args)
        }

        return queryResult
      }
    `
  }

  if (section.kind === "mutation") {
    return outdent`
      function ${entry.implementationHookName}() {
        const overrides = useApiDependencies()
        const override = ${entry.overridePath}
        const mutation = useMutation(${entry.referencePath})

        if (override) {
          return override()
        }

        return mutation
      }
    `
  }

  return outdent`
    function ${entry.implementationHookName}() {
      const overrides = useApiDependencies()
      const override = ${entry.overridePath}
      const action = useAction(${entry.referencePath})

      if (override) {
        return override()
      }

      return action
    }
  `
}

function renderHookApiObject(sections: HookApiModelSection[]) {
  return outdent`
    export const hookApi = {
      Provider: HookApiProvider,
      useDependencies: useApiDependencies,
      auth: {
        useActions: useAuthActions,
        useState: useAuthState,
      },
    ${sections.map(renderApiObjectSection).join("\n")}
    }
  `
}

function renderApiObjectSection(section: HookApiModelSection) {
  const moduleBlocks = section.modules.map((moduleDefinition) => {
    const exportLines = moduleDefinition.entries
      .map(
        (entry) =>
          outdent`
            ${entry.publicHookName}: ${entry.implementationHookName},
          `,
      )
      .join("\n")

    return outdent`
      ${moduleDefinition.name}: {
        ${exportLines}
      },
    `
  })

  return outdent`
    ${section.collectionName}: {
      ${moduleBlocks.join("\n")}
    },
  `
}

function stripStatementSemicolons(source: string) {
  return source.replace(/;$/gmu, "")
}
