/* eslint-disable */
/**
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run: bun ./packages/convex-hook-api/src/cli.ts generate
 */

import { api } from "../functions/_generated/api.js"
import { useAuthActions as useBaseConvexAuthActions } from "@convex-dev/auth/react"
import { useConvexAuth, useMutation, useQuery, type OptionalRestArgsOrSkip, type ReactMutation } from "convex/react"
import { FunctionReference } from "convex/server"
import { createContext, type ReactNode, useContext } from "react"
type QueryDependency<Query extends FunctionReference<"query">> = (...args: OptionalRestArgsOrSkip<Query>) => Query["_returnType"] | undefined
type MutationDependency<Mutation extends FunctionReference<"mutation">> = () => ReactMutation<Mutation>
type ConvexDependencies = {
  auth: {
    actions?: () => ReturnType<typeof useBaseConvexAuthActions>
    state?: () => ReturnType<typeof useConvexAuth>
  }
  queries?: {
    characters?: {
      getAppState?: QueryDependency<typeof api.characters.getAppState>
      getCharacterPageState?: QueryDependency<typeof api.characters.getCharacterPageState>
    }
  }
  mutations?: {
    characterSettings?: {
      upsertRogueSettings?: MutationDependency<typeof api.characterSettings.upsertRogueSettings>
    }
    characters?: {
      createCharacter?: MutationDependency<typeof api.characters.createCharacter>
      setActiveCharacter?: MutationDependency<typeof api.characters.setActiveCharacter>
      updateCharacter?: MutationDependency<typeof api.characters.updateCharacter>
    }
  }
}
const defaultHookApi = {}
const HookApiContext = createContext(defaultHookApi as ConvexDependencies)
function HookApiProvider({
  children,
  value
}: {
  children: ReactNode
  value: ConvexDependencies
}) {
  return <HookApiContext.Provider value={value}>{children}</HookApiContext.Provider>
}
function useApiDependencies() {
  return useContext(HookApiContext)
}
function useAuthActions() {
  const overrides = useApiDependencies()
  const authActions = useBaseConvexAuthActions()
  return overrides.auth?.actions?.() ?? authActions
}
function useAuthState() {
  const overrides = useApiDependencies()
  const authState = useConvexAuth()
  return overrides.auth?.state?.() ?? authState
}
function useCharactersAppStateQuery(...args: OptionalRestArgsOrSkip<typeof api.characters.getAppState>) {
  const overrides = useApiDependencies()
  const override = overrides.queries?.characters?.getAppState
  const queryResult = useQuery(api.characters.getAppState, args[0])
  if (override) {
    return override(...args)
  }
  return queryResult
}
function useCharactersCharacterPageStateQuery(...args: OptionalRestArgsOrSkip<typeof api.characters.getCharacterPageState>) {
  const overrides = useApiDependencies()
  const override = overrides.queries?.characters?.getCharacterPageState
  const queryResult = useQuery(api.characters.getCharacterPageState, args[0])
  if (override) {
    return override(...args)
  }
  return queryResult
}
function useCharacterSettingsUpsertRogueSettingsMutation() {
  const overrides = useApiDependencies()
  const override = overrides.mutations?.characterSettings?.upsertRogueSettings
  const mutation = useMutation(api.characterSettings.upsertRogueSettings)
  if (override) {
    return override()
  }
  return mutation
}
function useCharactersCreateCharacterMutation() {
  const overrides = useApiDependencies()
  const override = overrides.mutations?.characters?.createCharacter
  const mutation = useMutation(api.characters.createCharacter)
  if (override) {
    return override()
  }
  return mutation
}
function useCharactersSetActiveCharacterMutation() {
  const overrides = useApiDependencies()
  const override = overrides.mutations?.characters?.setActiveCharacter
  const mutation = useMutation(api.characters.setActiveCharacter)
  if (override) {
    return override()
  }
  return mutation
}
function useCharactersUpdateCharacterMutation() {
  const overrides = useApiDependencies()
  const override = overrides.mutations?.characters?.updateCharacter
  const mutation = useMutation(api.characters.updateCharacter)
  if (override) {
    return override()
  }
  return mutation
}
export const hookApi = {
  Provider: HookApiProvider,
  useDependencies: useApiDependencies,
  auth: {
    useActions: useAuthActions,
    useState: useAuthState
  },
  queries: {
    characters: {
      useAppState: useCharactersAppStateQuery,
      useCharacterPageState: useCharactersCharacterPageStateQuery
    }
  },
  mutations: {
    characterSettings: {
      useUpsertRogueSettings: useCharacterSettingsUpsertRogueSettingsMutation
    },
    characters: {
      useCreateCharacter: useCharactersCreateCharacterMutation,
      useSetActiveCharacter: useCharactersSetActiveCharacterMutation,
      useUpdateCharacter: useCharactersUpdateCharacterMutation
    }
  }
}
