import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

export type ConvexFunctionKind = "action" | "mutation" | "query"

export type ConvexModuleExport = {
  kind: ConvexFunctionKind
  name: string
}

export type ConvexModuleDefinition = {
  exports: ConvexModuleExport[]
  name: string
}

const generatedHeader = `/* eslint-disable */
/**
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run: bun run generate:convex-dependencies
 */`

export function readConvexModuleNames(sourceText: string) {
  return [...sourceText.matchAll(/import type \* as (\w+) from "\.\.\//g)].map(
    (match) => match[1],
  )
}

export function classifyConvexExports(
  sourceText: string,
): ConvexModuleExport[] {
  return [
    ...sourceText.matchAll(/export const (\w+) = (query|mutation|action)\(/g),
  ]
    .map((match) => ({
      kind: match[2] as ConvexFunctionKind,
      name: match[1],
    }))
    .sort((left, right) => left.name.localeCompare(right.name))
}

export function generateConvexDependenciesSource(
  modules: ConvexModuleDefinition[],
) {
  const queryModules = modules.filter((moduleDefinition) =>
    moduleDefinition.exports.some((entry) => entry.kind === "query"),
  )
  const mutationModules = modules.filter((moduleDefinition) =>
    moduleDefinition.exports.some((entry) => entry.kind === "mutation"),
  )
  const actionModules = modules.filter((moduleDefinition) =>
    moduleDefinition.exports.some((entry) => entry.kind === "action"),
  )
  const convexReactImports = [
    "useConvexAuth",
    "useMutation",
    "useQuery",
    "type OptionalRestArgsOrSkip",
    "type ReactMutation",
  ]

  if (actionModules.length > 0) {
    convexReactImports.unshift("useAction")
    convexReactImports.push("type ReactAction")
  }

  const dependencyTypeDefinitions = [
    `type QueryDependency<Query extends FunctionReference<"query">> = (
  ...args: OptionalRestArgsOrSkip<Query>
) => Query["_returnType"] | undefined`,
    `type MutationDependency<Mutation extends FunctionReference<"mutation">> =
  () => ReactMutation<Mutation>`,
    actionModules.length > 0
      ? `type ActionDependency<Action extends FunctionReference<"action">> =
  () => ReactAction<Action>`
      : null,
  ]
  const dependencySections = [
    renderDependencyTypeSection(queryModules, "query"),
    renderDependencyTypeSection(mutationModules, "mutation"),
    renderDependencyTypeSection(actionModules, "action"),
  ].filter((section) => section.length > 0)
  const generatedHooks = [
    renderGeneratedHooks(queryModules, "query"),
    renderGeneratedHooks(mutationModules, "mutation"),
    renderGeneratedHooks(actionModules, "action"),
  ].filter((section) => section.length > 0)
  const apiSections = [
    renderApiObjectSection(queryModules, "query"),
    renderApiObjectSection(mutationModules, "mutation"),
    renderApiObjectSection(actionModules, "action"),
  ].filter((section) => section.length > 0)

  return `${generatedHeader}

import { api } from "../../convex/_generated/api"
import { useAuthActions as useBaseConvexAuthActions } from "@convex-dev/auth/react"
import {
  ${convexReactImports.join(",\n  ")},
} from "convex/react"
import type { FunctionReference } from "convex/server"
import { createContext, type ReactNode, useContext } from "react"

${dependencyTypeDefinitions.filter((definition) => definition !== null).join("\n\n")}

type ConvexDependencies = {
  auth?: {
    actions?: () => ReturnType<typeof useBaseConvexAuthActions>
    state?: () => ReturnType<typeof useConvexAuth>
  }
${dependencySections.join("\n")}
}

const defaultConvexApi = {}

const ConvexApiContext = createContext<ConvexDependencies>(defaultConvexApi)

function ConvexApiProvider({
  children,
  value,
}: {
  children: ReactNode
  value: ConvexDependencies
}) {
  return (
    <ConvexApiContext.Provider value={value}>
      {children}
    </ConvexApiContext.Provider>
  )
}

function useApiDependencies() {
  return useContext(ConvexApiContext)
}

function useAuthActions() {
  const overrides = useApiDependencies()
  const authActions = useBaseConvexAuthActions()

  return overrides.auth?.actions?.() ?? authActions
}

function useAuthState() {
  const overrides = useApiDependencies()
  const authState = useConvexAuth()

  return overrides.auth?.state?.() ?? authState
}

${generatedHooks.join("\n\n")}

export const convexApi = {
  Provider: ConvexApiProvider,
  useDependencies: useApiDependencies,
  auth: {
    useActions: useAuthActions,
    useState: useAuthState,
  },
${apiSections.join("\n")}
}
`
}

function renderDependencyTypeSection(
  modules: ConvexModuleDefinition[],
  kind: ConvexFunctionKind,
) {
  if (modules.length === 0) {
    return ""
  }

  const collectionName = getCollectionName(kind)
  const dependencyType = getDependencyTypeName(kind)
  const moduleBlocks = modules.map((moduleDefinition) => {
    const exportsByKind = moduleDefinition.exports.filter(
      (entry) => entry.kind === kind,
    )

    if (exportsByKind.length === 0) {
      return null
    }

    const exportLines = exportsByKind
      .map((entry) =>
        formatDependencyReferenceLine(
          entry.name,
          dependencyType,
          `typeof api.${moduleDefinition.name}.${entry.name}`,
        ),
      )
      .join("\n")

    return `    ${moduleDefinition.name}?: {
${exportLines}
    }`
  })

  return `  ${collectionName}?: {
${moduleBlocks.filter((block) => block !== null).join("\n")}
  }`
}

function renderGeneratedHooks(
  modules: ConvexModuleDefinition[],
  kind: ConvexFunctionKind,
) {
  return modules
    .flatMap((moduleDefinition) =>
      moduleDefinition.exports
        .filter((entry) => entry.kind === kind)
        .map((entry) =>
          renderGeneratedHook(kind, moduleDefinition.name, entry.name),
        ),
    )
    .join("\n\n")
}

function renderGeneratedHook(
  kind: ConvexFunctionKind,
  moduleName: string,
  exportName: string,
) {
  const implementationHookName = toImplementationHookName(
    moduleName,
    exportName,
    kind,
  )
  const referencePath = `api.${moduleName}.${exportName}`
  const overridePath = `overrides.${getCollectionName(kind)}?.${moduleName}?.${exportName}`

  if (kind === "query") {
    return `function ${implementationHookName}(
  ...args: OptionalRestArgsOrSkip<typeof ${referencePath}>
) {
  const overrides = useApiDependencies()
  const override = ${overridePath}
  const queryResult = useQuery(${referencePath}, args[0])

  if (override) {
    return override(...args)
  }

  return queryResult
}`
  }

  if (kind === "mutation") {
    return `function ${implementationHookName}() {
  const overrides = useApiDependencies()
  const override = ${overridePath}
  const mutation = useMutation(${referencePath})

  if (override) {
    return override()
  }

  return mutation
}`
  }

  return `function ${implementationHookName}() {
  const overrides = useApiDependencies()
  const override = ${overridePath}
  const action = useAction(${referencePath})

  if (override) {
    return override()
  }

  return action
}`
}

function renderApiObjectSection(
  modules: ConvexModuleDefinition[],
  kind: ConvexFunctionKind,
) {
  if (modules.length === 0) {
    return ""
  }

  const collectionName = getCollectionName(kind)
  const moduleBlocks = modules.map((moduleDefinition) => {
    const exportsByKind = moduleDefinition.exports.filter(
      (entry) => entry.kind === kind,
    )

    if (exportsByKind.length === 0) {
      return null
    }

    const exportLines = exportsByKind
      .map(
        (entry) =>
          `${toPublicHookName(entry.name, kind)}: ${toImplementationHookName(moduleDefinition.name, entry.name, kind)},`,
      )
      .join("\n      ")

    return `    ${moduleDefinition.name}: {
      ${exportLines}
    },`
  })

  return `  ${collectionName}: {
${moduleBlocks.filter((block) => block !== null).join("\n")}
  },`
}

function getCollectionName(kind: ConvexFunctionKind) {
  return kind === "query" ? "queries" : `${kind}s`
}

function getDependencyTypeName(kind: ConvexFunctionKind) {
  return kind === "query"
    ? "QueryDependency"
    : kind === "mutation"
      ? "MutationDependency"
      : "ActionDependency"
}

function toImplementationHookName(
  moduleName: string,
  exportName: string,
  kind: ConvexFunctionKind,
) {
  return `use${toPascalCase(moduleName)}${toPascalCase(trimPrefix(exportName, kind))}${kind === "query" ? "Query" : toPascalCase(kind)}`
}

function toPublicHookName(exportName: string, kind: ConvexFunctionKind) {
  return `use${toPascalCase(trimPrefix(exportName, kind))}`
}

function trimPrefix(name: string, kind: ConvexFunctionKind) {
  if (kind === "query" && name.startsWith("get") && name.length > 3) {
    return `${name[3].toLowerCase()}${name.slice(4)}`
  }

  return name
}

function toPascalCase(value: string) {
  return value.replace(
    /(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g,
    (_match, _prefix, char: string) => char.toUpperCase(),
  )
}

function formatDependencyReferenceLine(
  propertyName: string,
  dependencyType: string,
  referenceType: string,
) {
  const singleLine = `      ${propertyName}?: ${dependencyType}<${referenceType}>`

  if (singleLine.length <= 80) {
    return singleLine
  }

  return `      ${propertyName}?: ${dependencyType}<
        ${referenceType}
      >`
}

export async function writeConvexDependenciesFile(projectRoot: string) {
  const apiDeclarationPath = path.join(
    projectRoot,
    "convex/_generated/api.d.ts",
  )
  const apiDeclaration = await readFile(apiDeclarationPath, "utf8")
  const moduleNames = readConvexModuleNames(apiDeclaration)
  const modules = await Promise.all(
    moduleNames.map(async (moduleName) => {
      const modulePath = path.join(projectRoot, `convex/${moduleName}.ts`)
      const moduleSource = await readFile(modulePath, "utf8")

      return {
        exports: classifyConvexExports(moduleSource),
        name: moduleName,
      } satisfies ConvexModuleDefinition
    }),
  )

  const outputPath = path.join(projectRoot, "src/generated/convex-api.tsx")

  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, generateConvexDependenciesSource(modules))
}

if (import.meta.main) {
  const projectRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
  )
  await writeConvexDependenciesFile(projectRoot)
}
